### ISSUE TITLE
У 2-го КВУ слишком большой DR 

### ISSUE THREAD

**Issue by Gibitop** [HackMemory/BasicComputer#2]
Не берусь утверждать, но на сколько мне известно, устройства ввода имеют DR размером 1 байт, то есть две тетрады. В новой версии в КВУ 2 DR имеет размер 2 байта.
![Screenshot from 2020-05-23 15-03-19](https://user-images.githubusercontent.com/20557300/82730211-ccd38400-9d06-11ea-8d56-8950797e7115.png)

**Comment by HackMemory** [comment]
исправил
